#-----------------------------------------------------------------------
#---------------------------欢迎使用EWE----------------------------------
#------------------------未经允许不得转载,倒卖-----------------------------
#------------------------转载联系作者EthanAxe----------------------------
#-----------------------------------------------------------------------

#所有自定义消息都支持颜色显示“§”使用“\n”来换行,支持PAPI变量!

#玩家加入自定义消息
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
#------------------------关于玩家加入/退出服务器消息-----------------------
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
joinmsg:
  #true为开启 false为关闭！
  enabled: true
  #这里可以自定义消息
  joinMessage: "§f[§7§lEWE§f]§d欢迎§e§n%player_name%§b加入了服务器！\n§f[§7§lEWE§f]§c支持多行§f,§c请在配置文件自行调整!"

#玩家退出自定义消息
quitmsg:
  #true为开启 false为关闭！
  enabled: true
  #这里可以自定义消息
  quitMessage: "§f[§7§lEWE§f]§a%player_name% §c退出了服务器"

#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
#------------------------关于玩家聊天消息--------------------------------
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
#玩家聊天自定义
chatmsg:
  #true为开启 false为关闭！
  enabled: true
  #设置玩家名字支持PAPI变量
  chatplayer: "§f[§7EWE§f] [§b%player_name%§f] §7> "
  #自定义设置玩家聊天！！！不支持PAPI变量！！！如果添加报错请修改为'$message$'可以添加一些固定文字的！
  chatmessage: "§a$message$"

#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
#------------------------关于玩家死亡消息--------------------------------
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
#玩家死亡时自定义消息
death:
  #true为开启 false为关闭！
  enabled: true
  #这里可以自定义消息
  deathmessage: "§f[§7§lEWE§f]§a§n%player_name%§c与世长辞,让我们为他哀悼!"

#是否在玩家死亡时向玩家本人发送死亡点坐标 true为开启 false为关闭！
pos:
  #true为开启 false为关闭！
  enabled: true
  #这里可以自定义消息
  message: "§f[§7§lEWE§f]§c你的死亡点在§6§n%player_x%§f , §6§n%player_y%§f , §6§n%player_z%!"