#-----------------------------------------------------------------------
#---------------------------欢迎使用EWE----------------------------------
#------------------------未经允许不得转载,倒卖-----------------------------
#------------------------转载联系作者EthanAxe----------------------------
#-----------------------------------------------------------------------

#所有自定义消息都支持颜色显示“§”使用“\n”来换行,支持PAPI变量!

#玩家加入自定义消息
joinmsg:
  #true为开启 false为关闭！
  enabled: true
  #这里可以自定义消息
  joinMessage: "§f[§7§lEWE§f]§d欢迎§e§n%player_name%§b加入了服务器！\n§f[§7§lEWE§f]§c支持多行§f,§c请在配置文件自行调整!"

#玩家退出自定义消息
quitmsg:
  #true为开启 false为关闭！
  enabled: true
  #这里可以自定义消息
  quitMessage: "§f[§7§lEWE§f]§a%player_name% §c退出了服务器"

#玩家死亡时自定义消息
death:
  #true为开启 false为关闭！
  enabled: true
  #这里可以自定义消息
  deathmessage: "§f[§7§lEWE§f]§a§n%player_name%§c与世长辞,让我们为他哀悼!"

#是否在玩家死亡时向玩家本人发送死亡点坐标 true为开启 false为关闭！
pos:
  #true为开启 false为关闭！
  enabled: true
  #这里可以自定义消息
  message: "§f[§7§lEWE§f]§c你的死亡点在§6§n%player_x%§f , §6§n%player_y%§f , §6§n%player_z%!"